### ISSUE TITLE
Terminal loses its mind if you run 'clear'

### ISSUE THREAD

**Issue by anaisbetts** [atom-archive/terminal#11]
Get a decent terminal buffer going, then type 'clear'. There will be a ton of whitespace with stuff floating in the middle, new commands scroll around strangely, etc etc

**Comment by mcolyer** [comment]
Clear seems to work for me. Are you still seeing this?

**Comment by rougeth** [comment]
'clear' works here.

**Comment by anaisbetts** [comment]
Gonna close this, I'll reopen if I see it again
