### ISSUE TITLE
"Open Terminal" opens up the web inspector

### ISSUE THREAD

**Issue by teoljungberg** [atom-archive/terminal#21]
On atom 0.60.0 and `HEAD` of atom/terminal

**Comment by ianseyer** [comment]
Replicated on fresh install

**Comment by bsradcliffe** [comment]
Same issue here. Hotkey and terminal:open both exhibit this behavior.

**Comment by nathansobo** [comment]
Could you paste the stack trace from the console?

**Comment by nathansobo** [comment]
Make sure you `apm install` in the terminal directory to get its dependencies.

**Comment by bsradcliffe** [comment]
Feeling dumb now. That resolved it for me. I hadn't installed it via apm, I'd just cloned it directly here from the repo. Thanks, @nathansobo. :+1:  I'd consider this one closed.

**Comment by nathansobo** [comment]
No problem at all. Don't feel dumb.
