### ISSUE TITLE
Doesn't open

### ISSUE THREAD

**Issue by johnpaulmedina** [atom-archive/terminal#22]
The command keys fail to launch terminal but instead open the Dev Tools window. I tried switching the command keys but still only opens Dev Tools.

**Comment by GerritWanderer** [comment]
I've the same issue

**Comment by aspires** [comment]
Are you installing your dependencies properly? That was my problem: see #21

**Comment by johnpaulmedina** [comment]
Ughh so dumb.. Thanks dude I thought everything came with their respective dependencies. Commit to memory.

**Comment by johnpaulmedina** [comment]
jp@John-Pauls-MacBook-Pro ~/.atom/packages/terminal $ apm install

gyp info it worked if it ends with ok
gyp info using node-gyp@0.12.2
gyp info using node@0.10.26 | darwin | x64
gyp http GET https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.11.10/node-v0.11.10.tar.gz
gyp http 200 https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.11.10/node-v0.11.10.tar.gz
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: EPERM, utime '/Users/jp/.atom/.node-gyp/.node-gyp/0.11.10'
gyp ERR! System Darwin 13.1.0
gyp ERR! command "/usr/local/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=0.11.10" "--dist-url=https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist" "--arch=x64"
gyp ERR! cwd /Users/jp/.atom
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     https://github.com/TooTallNate/node-gyp/issues

**Comment by adrianlee44** [comment]
Seems like there is a permission problem with your Atom cache folder, `/Users/jp/.atom/`. Changing the owner or adding write permission might help.

**Comment by rougeth** [comment]
I have the same problem. I already changed the owner and added write permission, but it didn't work.

**Edited**: I reinstalled Atom (0.65.0) and now _apm install_ works.
