### ISSUE TITLE
Error installing the package within Atom in OSX 10.8.5

### ISSUE THREAD

**Issue by JohnPostlethwait** [atom-archive/terminal#28]
```
> pty.js@0.2.4 install /private/var/folders/_5/08pzzpxs7759c6m5cjchdwqc0000gn/T/apm-install-dir-114222-808-ud9mby/node_modules/terminal/node_modules/pty.js
> node-gyp rebuild


npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/guid/0.0.10
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/fs-plus
npm http GET http://gh-contractor-zcbenz.s3.amazonaws.com/temp/pty.js-0.2.4.tgz
npm http 200 http://gh-contractor-zcbenz.s3.amazonaws.com/temp/pty.js-0.2.4.tgz
npm http 200 https://registry.npmjs.org/guid/0.0.10
npm http GET https://registry.npmjs.org/guid/-/guid-0.0.10.tgz
npm http 200 https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/underscore-plus/-/underscore-plus-1.1.0.tgz
npm http 200 https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/emissary/-/emissary-1.2.0.tgz
npm http 200 https://registry.npmjs.org/fs-plus
npm http GET https://registry.npmjs.org/fs-plus/-/fs-plus-2.0.4.tgz
npm http 200 https://registry.npmjs.org/guid/-/guid-0.0.10.tgz
npm http 200 https://registry.npmjs.org/underscore-plus/-/underscore-plus-1.1.0.tgz
npm http 200 https://registry.npmjs.org/fs-plus/-/fs-plus-2.0.4.tgz
npm http 200 https://registry.npmjs.org/emissary/-/emissary-1.2.0.tgz
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/property-accessors
npm http GET https://registry.npmjs.org/nan/0.7.0
npm http GET https://registry.npmjs.org/extend
npm http 200 https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/underscore/-/underscore-1.5.2.tgz
npm http 200 https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.5.tgz
npm http 200 https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/mixto/-/mixto-1.0.0.tgz
npm http 200 https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/rimraf/-/rimraf-2.2.6.tgz
npm http 200 https://registry.npmjs.org/nan/0.7.0
npm http GET https://registry.npmjs.org/nan/-/nan-0.7.0.tgz
npm http 200 https://registry.npmjs.org/property-accessors
npm http GET https://registry.npmjs.org/property-accessors/-/property-accessors-1.1.0.tgz
npm http 200 https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/extend/-/extend-1.2.1.tgz
npm http 200 https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.5.tgz
npm http 200 https://registry.npmjs.org/mixto/-/mixto-1.0.0.tgz
npm http 200 https://registry.npmjs.org/underscore/-/underscore-1.5.2.tgz
npm http 200 https://registry.npmjs.org/rimraf/-/rimraf-2.2.6.tgz
npm http 200 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/async/-/async-0.2.10.tgz
npm http 200 https://registry.npmjs.org/extend/-/extend-1.2.1.tgz
npm http 200 https://registry.npmjs.org/property-accessors/-/property-accessors-1.1.0.tgz
npm http 200 https://registry.npmjs.org/nan/-/nan-0.7.0.tgz
npm http 200 https://registry.npmjs.org/async/-/async-0.2.10.tgz
/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/node-gyp-bin/node-gyp: line 2: node: command not found
npm ERR! pty.js@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the pty.js@0.2.4 install script.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 12.5.0
npm ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/bin/node_darwin_x64" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--userconfig" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/.apmrc" "install" "/var/folders/_5/08pzzpxs7759c6m5cjchdwqc0000gn/T/d-114222-808-1wjyqrw/package.tgz" "--target=0.11.10" "--arch=x64"
npm ERR! cwd /private/var/folders/_5/08pzzpxs7759c6m5cjchdwqc0000gn/T/apm-install-dir-114222-808-ud9mby
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.4
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /private/var/folders/_5/08pzzpxs7759c6m5cjchdwqc0000gn/T/apm-install-dir-114222-808-ud9mby/npm-debug.log
npm ERR! not ok code 0
```

**Comment by mattstyles** [comment]
Yeah, I just got the same error with terminal@0.28.0

**Comment by fclement21** [comment]
Same error too

**Comment by ksmth** [comment]
I had success installing this plugin by running `apm install terminal` from the command line instead of the GUI.

**Comment by fclement21** [comment]
I try to install with apm install terminal and I have the same error.

**Comment by mattstyles** [comment]
@ksmith yeah that worked a treat.  I normally install from command line, not sure why I went GUI this time, but, in any case installing terminal from terminal worked a treat (its struggling with my .zsh config but thats a separate issue)

thanks

**Comment by mignev** [comment]
Same to me via GUI, but with apm was okay!

**Comment by ksmth** [comment]
@fclement21 You posted a different error before and have removed it since. Do you get a different error now or is it exactly the same as the above?

**Comment by fils** [comment]
I tried the apm command line and got an error about not finding a util.h file.  This is associated with a UNIX pty.  Is there some developer package for terminal that is needed?  I am on Mac OS X 10.9.2.

```
Doug-Fils-MacBook-Pro:~ dfils$ apm install terminal
Installing terminal to /Users/dfils/.atom/packages ✗

> pty.js@0.2.4 install /private/var/folders/2j/sszkxk093q9b5wk30wctwlz0000133/T/apm-install-dir-114226-82088-64qg1t/node_modules/terminal/node_modules/pty.js
> node-gyp rebuild

  CXX(target) Release/obj.target/pty/src/unix/pty.o

npm http GET https://registry.npmjs.org/guid/0.0.10
npm http GET http://gh-contractor-zcbenz.s3.amazonaws.com/temp/pty.js-0.2.4.tgz
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/fs-plus
npm http 200 http://gh-contractor-zcbenz.s3.amazonaws.com/temp/pty.js-0.2.4.tgz
npm http 304 https://registry.npmjs.org/guid/0.0.10
npm http 304 https://registry.npmjs.org/emissary
npm http 304 https://registry.npmjs.org/fs-plus
npm http 304 https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/property-accessors
npm http GET https://registry.npmjs.org/nan/0.7.0
npm http GET https://registry.npmjs.org/extend
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/nan/0.7.0
npm http 304 https://registry.npmjs.org/extend
npm http 304 https://registry.npmjs.org/property-accessors
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/mixto
../src/unix/pty.cc:37:10: fatal error: '/usr/include/util.h' file not found
#include </usr/include/util.h>
         ^
1 error generated.
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Darwin 13.1.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/2j/sszkxk093q9b5wk30wctwlz0000133/T/apm-install-dir-114226-82088-64qg1t/node_modules/terminal/node_modules/pty.js
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm ERR! pty.js@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.2.4 install script.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.1.0
npm ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/bin/node_darwin_x64" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--userconfig" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/.apmrc" "install" "/Users/dfils/.atom/.node-gyp/.atom/.apm/terminal/0.28.0/package.tgz" "--target=0.11.10" "--arch=x64"
npm ERR! cwd /private/var/folders/2j/sszkxk093q9b5wk30wctwlz0000133/T/apm-install-dir-114226-82088-64qg1t
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.4
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /private/var/folders/2j/sszkxk093q9b5wk30wctwlz0000133/T/apm-install-dir-114226-82088-64qg1t/npm-debug.log
npm ERR! not ok code 0
```

**Comment by ksmth** [comment]
I'd try installing Xcode and the command line tools if you haven't done that already. You can download Xcode from the App Store and install the utilities from within Xcode if I remember correctly. —

**Comment by fils** [comment]
ksmth  that was it..  forgot the newer Xcodes don't install those by default.

Use:  xcode-select --install  
to install the command line utils then you can install the package.

**Comment by santiblanko** [comment]
running apm install terminal :+1:

**Comment by mattstyles** [comment]
@fclement21 just saw an error about `node-gyp` that has been removed?  still having problems with it?

From the stack trace it looks like there is a conflict between `node-gyp` v0.12 and v0.11, looks like it cant find something and is trying to install an old version. Have you tried reinstalling `node-gyp` globally? This should probably be v0.12. I think `apm` uses a local version though, you can check `apm`'s version at `Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/node-gyp/package.json`, if that _isnt't_ v0.12 then you might want to try reinstalling `apm` as well.

**Comment by luuuc** [comment]
Hi,

Atoms ~/.atom/.node-gyp seems to have wrong permissions. 
Deleting the folder `sudo rm -rf ~/.atom/.node-gyp` should fix this issue.

Hope this helps ...or not :-)

**Comment by matcouto** [comment]
Same error when installing through Package manager

Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/node-gyp-bin/node-gyp: line 2: node: command not found
npm ERR! pty.js@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the pty.js@0.2.4 install script.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

**Comment by johnbona** [comment]
I had both errors (pty.js and util.h) when trying to install from the command line. This is what I had to do for terminal to be installed without any errors:
1. Update the node-gyp package globally
   
   ``` bash
   sudo npm update -g node-gyp
   ```
2. Delete Atom’s node-gyp package (Thanks @nerdlab!)
   
   ``` bash
   sudo rm -rf ~/.atom/.node-gyp
   ```
3. If you’re using 10.8, install the Xcode Command Line Tools from the command line (Thanks @fils!)
   
   ``` bash
   xcode-select --install
   ```
   
   If you’re using 10.9, install the Xcode Command Line Tools by downloading them from the Apple Developer site [right here](https://developer.apple.com/downloads/index.action?name=Command%20Line%20Tools%20%28OS%20X%20Mavericks%29) (Thanks @FireZenk!)
4. Now install the terminal package from the command line (Thanks @ksmth!)
   
   ``` bash
   apm install terminal
   ```

**Comment by cognitom** [comment]
Try to open Atom from Terminal app.

``` bash
$ atom
```

Now you can install this package within Atom GUI. It may depend on whitch process spawns Atom. (launchd or yours)

FYI, check this discussion. https://github.com/rgbkrk/atom-script/issues/61

**Comment by Glavin001** [comment]
Thanks, @ksmth and others for your help.
The following worked for me:

``` bash
apm install terminal
```

From https://github.com/atom/terminal/issues/28#issuecomment-38562442

**Comment by Grawl** [comment]
It fixes terminal install but not fixes installation from UI. Anyone have a solution?

**Comment by cognitom** [comment]
Atom launched via GUI doesn't know PATH to Node.js. Spawning a new process with bash_profile in installation can be a way to solve it.

**Comment by FireZenk** [comment]
@johnbona Step 3 doesn't work on Mavericks instead of that you need to download manually the Command Line tools forma Apple's developer site.

**Comment by johnbona** [comment]
@FireZenk Just updated my original comment with your instructions.

**Comment by gnilrets** [comment]
apm install terminal doesn't seem to work for me.  Very new to atom.  What am I missing?

```
[- terminal -] apm install terminal
Installing terminal to /Users/gnilrets/.atom/packages ✗
Request for package information failed: Not Found
```

**Comment by behrtam** [comment]
The same for me ...

```
mba-ta:packages tmo$ apm install terminal
Installing terminal to /Users/tmo/.atom/packages ✗
Request for package information failed: Not Found

mba-ta:packages tmo$ apm --version
apm  0.57.0
npm  1.4.4
node 0.10.26
```

**Comment by probablycorey** [comment]
Sorry for the confusion. I removed the terminal package from the apm package registry awhile ago. Since this is an experimental package that we are not actively maintaining, it seemed disingenuous to have it in the package store.

But you can still install the package manually.

``` sh
git clone https://github.com/atom/terminal.git
cd terminal
apm install
apm link # this will add a symlink to $HOME/.atom/packages
```

**Comment by JonathanSchndr** [comment]
thanks @luuuc its fixed my problem.

**Comment by furryfury** [comment]
I'm getting this error ;

Last login: Wed Feb 17 17:12:06 on ttys000
/Applications/Atom.app/Contents/MacOS/Atom ; exit;
mkdir: /Users/dopeboyfresh/.bash_sessions: Operation not permitted
touch: /Users/dopeboyfresh/.bash_sessions/B028012D-B3BE-4616-8C78-31C4D71FEEA3.historynew: No such file or directory
Rebeccas-MacBook-Pro:~ dopeboyfresh$ /Applications/Atom.app/Contents/MacOS/Atom ; exit;
2016-02-17 17:22:11.868 Atom[1402:68882] EPERM: operation not permitted, mkdir '/Users/dopeboyfresh/.atom'
2016-02-17 17:22:11.875 Atom[1402:68882] Error: EPERM: operation not permitted, mkdir '/Users/dopeboyfresh/.atom'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:799:18)
    at Function.sync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:55:12)
    at Object.fsPlus.makeTreeSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:343:23)
    at Config.module.exports.Config.initializeConfigDirectory (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:427:10)
    at Config.module.exports.Config.load (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:412:12)
    at new AutoUpdateManager (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/auto-update-manager.js:50:19)
    at new AtomApplication (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:102:32)
    at createAtomApplication (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:60:16)
    at Function.module.exports.AtomApplication.open (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:63:9)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/main.js:55:23)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
