### ISSUE TITLE
Switching from the terminal tab to other tab would make the terminal clear

### ISSUE THREAD

**Issue by zcbenz** [atom-archive/terminal#4]
How to reproduce:
1. open terminal
2. switch to other tab
3. switch back to terminal tab
4. the terminal tab is now cleared

![authopen](https://f.cloud.github.com/assets/639601/740610/a5828f40-e37c-11e2-9ef7-2dd61047fdf3.gif)

**Comment by kevinsawicki** [comment]
I think this may have been fixed in https://github.com/github/atom/commit/b786bcc7746136c270fddb2c04ab47704231b9af, can you verify you are seeing this on or past that commit?

**Comment by zcbenz** [comment]
After pulling the latest atom, this problem has been gone, thanks!
