### ISSUE TITLE
Opening two Terminals only creates a single Terminal session

### ISSUE THREAD

**Issue by mutle** [atom-archive/terminal#5]
This has to do with using `terminal://<path>` URLs. It doesn't look like the `nextTerminalId` included in the URL keeps atom from using the same model for the second terminal view.

@kevinsawicki Any suggestions on how to solve this?

**Comment by kevinsawicki** [comment]
I'm not sure I understand the issue, `nextTerminalId` is no longer used in master.

Are you unable to create two terminal sessions from the event palette or are you opening them another way?

Sorry if I'm missing something.

**Comment by mutle** [comment]
Oops, looks like I was not on master. Confirmed working on master.
