### ISSUE TITLE
Install Error on Yosemite 10.10.1

### ISSUE THREAD

**Issue by ghost** [atom-archive/terminal#52]
I'm Getting this error while running this code on terminal folder inside packages:

> apm install 

----------------------ERROR LOG-------------------------------

> pty.js@0.2.4 install /Users/user/.atom/packages/terminal/node_modules/pty.js
> node-gyp rebuild
> 
> CXX(target) Release/obj.target/pty/src/unix/pty.o
> 
> npm http GET http://gh-contractor-zcbenz.s3.amazonaws.com/temp/pty.js-0.2.4.tgz
> npm http 200 http://gh-contractor-zcbenz.s3.amazonaws.com/temp/pty.js-0.2.4.tgz
> npm http GET https://registry.npmjs.org/nan/0.7.0
> npm http GET https://registry.npmjs.org/extend
> npm http 200 https://registry.npmjs.org/nan/0.7.0
> npm http GET https://registry.npmjs.org/nan/-/nan-0.7.0.tgz
> npm http 200 https://registry.npmjs.org/extend
> npm http GET https://registry.npmjs.org/extend/-/extend-1.2.1.tgz
> npm http 200 https://registry.npmjs.org/nan/-/nan-0.7.0.tgz
> npm http 200 https://registry.npmjs.org/extend/-/extend-1.2.1.tgz
> 2015-01-07 07:17:35.375 xcodebuild[12934:317873] [MT] PluginLoading: Required plug-in compatibility UUID C4A681B0-4A26-480E-93EC-1218098B9AA0 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
> In file included from ../src/unix/pty.cc:16:
> ../node_modules/nan/nan.h:352:13: error: no member named 'New' in 'v8::String'
> return  _NAN_ERROR(v8::Exception::Error, errmsg);
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../node_modules/nan/nan.h:332:50: note: expanded from macro '_NAN_ERROR'
> # define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
> 
> ``` ^
> ../node_modules/nan/nan.h:356:5: error: no member named 'ThrowException' in namespace 'v8'
> _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../node_modules/nan/nan.h:337:11: note: expanded from macro '_NAN_THROW_ERROR'
> v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
> ~~~~^
> ../node_modules/nan/nan.h:356:5: error: no member named 'New' in 'v8::String'
> _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../node_modules/nan/nan.h:337:26: note: expanded from macro '_NAN_THROW_ERROR'
> v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
> ^~~~~~~~~~~~~~~~~~~~~~~
> ../node_modules/nan/nan.h:332:50: note: expanded from macro '_NAN_ERROR'
> # define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
> ~~~~~~~~~~~~^
> ../node_modules/nan/nan.h:361:9: error: no type named 'ThrowException' in namespace 'v8'
> v8::ThrowException(error);
> ~~~~^
> ../node_modules/nan/nan.h:368:65: error: no member named 'New' in 'v8::String'
> v8::Local<v8::Value> err = v8::Exception::Error(v8::String::New(msg));
> ~~~~~~~~~~~~^
> ../node_modules/nan/nan.h:370:26: error: no member named 'New' in 'v8::String'
> obj->Set(v8::String::New("code"), v8::Int32::New(errorNumber));
> ~~~~~~~~~~~~^
> ../node_modules/nan/nan.h:382:12: error: no member named 'New' in 'v8::String'
> return _NAN_ERROR(v8::Exception::TypeError, errmsg);
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../node_modules/nan/nan.h:332:50: note: expanded from macro '_NAN_ERROR'
> # define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
> ~~~~~~~~~~~~^
> ../node_modules/nan/nan.h:386:5: error: no member named 'ThrowException' in namespace 'v8'
> _NAN_THROW_ERROR(v8::Exception::TypeError, errmsg);
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../node_modules/nan/nan.h:337:11: note: expanded from macro '_NAN_THROW_ERROR'
> v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
> ~~~~^
> ../node_modules/nan/nan.h:386:5: error: no member named 'New' in 'v8::String'
> _NAN_THROW_ERROR(v8::Exception::TypeError, errmsg);
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../node_modules/nan/nan.h:337:26: note: expanded from macro '_NAN_THROW_ERROR'
> v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
> ^~~~~~~~~~~~~~~~~~~~~~~
> ../node_modules/nan/nan.h:332:50: note: expanded from macro '_NAN_ERROR'
> # define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
> ~~~~~~~~~~~~^
> ../node_modules/nan/nan.h:390:12: error: no member named 'New' in 'v8::String'
> return _NAN_ERROR(v8::Exception::RangeError, errmsg);
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../node_modules/nan/nan.h:332:50: note: expanded from macro '_NAN_ERROR'
> # define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
> ~~~~~~~~~~~~^
> ../node_modules/nan/nan.h:394:5: error: no member named 'ThrowException' in namespace 'v8'
> _NAN_THROW_ERROR(v8::Exception::RangeError, errmsg);
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../node_modules/nan/nan.h:337:11: note: expanded from macro '_NAN_THROW_ERROR'
> v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
> ~~~~^
> ../node_modules/nan/nan.h:394:5: error: no member named 'New' in 'v8::String'
> _NAN_THROW_ERROR(v8::Exception::RangeError, errmsg);
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../node_modules/nan/nan.h:337:26: note: expanded from macro '_NAN_THROW_ERROR'
> v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
> ^~~~~~~~~~~~~~~~~~~~~~~
> ../node_modules/nan/nan.h:332:50: note: expanded from macro '_NAN_ERROR'
> # define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
> ~~~~~~~~~~~~^
> ../node_modules/nan/nan.h:714:49: error: too few arguments to function call, single argument 'isolate' was not specified
> v8::Local<v8::Object> obj = v8::Object::New();
> ~~~~~~~~~~~~~~~ ^
> /Users/user/.atom/.node-gyp/.node-gyp/0.18.0/deps/v8/include/v8.h:2388:3: note: 'New' declared here
> static Local<Object> New(Isolate* isolate);
> ^
> In file included from ../src/unix/pty.cc:16:
> ../node_modules/nan/nan.h:720:49: error: too few arguments to function call, single argument 'isolate' was not specified
> v8::Local<v8::Object> obj = v8::Object::New();
> ~~~~~~~~~~~~~~~ ^
> /Users/user/.atom/.node-gyp/.node-gyp/0.18.0/deps/v8/include/v8.h:2388:3: note: 'New' declared here
> static Local<Object> New(Isolate* isolate);
> ^
> In file included from ../src/unix/pty.cc:16:
> ../node_modules/nan/nan.h:727:12: error: no member named 'Dispose' in 'v8::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
> handle.Dispose();
> ~~~~~~ ^
> ../node_modules/nan/nan.h:728:12: error: no member named 'Clear' in 'v8::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
> handle.Clear();
> ~~~~~~ ^
> ../node_modules/nan/nan.h:733:39: error: no member named 'NewSymbol' in 'v8::String'; did you mean 'IsSymbol'?
> NanPersistentToLocal(handle)->Set(NanSymbol("callback"), fn);
> ^~~~~~~~~~~~~~~~~~~~~
> ../node_modules/nan/nan.h:169:38: note: expanded from macro 'NanSymbol'
> #define NanSymbol(value) v8::String::NewSymbol(value)
> ~~~~~~~~~~~~^
> /Users/user/.atom/.node-gyp/.node-gyp/0.18.0/deps/v8/include/v8.h:1379:8: note: 'IsSymbol' declared here
> bool IsSymbol() const;
> ^
> In file included from ../src/unix/pty.cc:16:
> ../node_modules/nan/nan.h:733:39: error: call to non-static member function without an object argument
> NanPersistentToLocal(handle)->Set(NanSymbol("callback"), fn);
> ^~~~~~~~~~~~~~~~~~~~~
> ../node_modules/nan/nan.h:169:38: note: expanded from macro 'NanSymbol'
> #define NanSymbol(value) v8::String::NewSymbol(value)
> ~~~~~~~~~~~~^~~~~~~~~
> ../node_modules/nan/nan.h:737:46: error: no member named 'NewSymbol' in 'v8::String'; did you mean 'IsSymbol'?
> return NanPersistentToLocal(handle)->Get(NanSymbol("callback"))
> ^~~~~~~~~~~~~~~~~~~~~
> ../node_modules/nan/nan.h:169:38: note: expanded from macro 'NanSymbol'
> #define NanSymbol(value) v8::String::NewSymbol(value)
> ~~~~~~~~~~~~^
> /Users/user/.atom/.node-gyp/.node-gyp/0.18.0/deps/v8/include/v8.h:1379:8: note: 'IsSymbol' declared here
> bool IsSymbol() const;
> ^
> fatal error: too many errors emitted, stopping now [-ferror-limit=]
> 20 errors generated.
> make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
> gyp ERR! System Darwin 14.0.0
> gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /Users/user/.atom/packages/terminal/node_modules/pty.js
> gyp ERR! node -v v0.10.33
> gyp ERR! node-gyp -v v0.12.2
> gyp ERR! not ok 
> npm ERR! pty.js@0.2.4 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the pty.js@0.2.4 install script.
> npm ERR! This is most likely a problem with the pty.js package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls pty.js
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! System Darwin 14.0.0
> npm ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/.apmrc" "--userconfig" "/Users/user/.atom/.apmrc" "install" "--target=0.18.0" "--arch=x64"
> npm ERR! cwd /Users/user/.atom/packages/terminal
> npm ERR! node -v v0.10.33
> npm ERR! npm -v 1.4.4
> npm ERR! code ELIFECYCLE
> npm ERR! 
> npm ERR! Additional logging details can be found in:
> npm ERR!     /Users/user/.atom/packages/terminal/npm-debug.log
> npm ERR! not ok code 0
> ----------------------ERROR LOG-------------------------------
> ```

Osx Version: Yosemite 10.10.1
Atom Version: 0.165.0
NPM Version: 1.4.4
Node Version: 0.10.33
APM Version: 0.116.0

**Comment by ghost** [comment]
I Fix that problem installing node-gyp 

But now when i open an terminal tab, i get a white screen

**Comment by sadovnychyi** [comment]
Same here, cannot get it working. :broken_heart:

**Comment by felixphew** [comment]
Me three - can't even install. Is this even maintained anymore?

**Comment by floringogianu** [comment]
I think all the terminal emulators for atom out there depend on this right now: chjj/pty.js#103

**Comment by felixphew** [comment]
@floringogianu So there's nothing to do but sit tight and hope for the best, or is there a workaround?

**Comment by Raynes** [comment]
Looks like sit tight and hope for the best.

**Comment by lee-dohm** [comment]
All repositories in the [atom-archive organization](https://github.com/atom-archive) are unmaintained and deprecated. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
