### ISSUE TITLE
RIP Atom-terminal???

### ISSUE THREAD

**Issue by ghost** [atom-archive/terminal#54]
I see that this doesn't have any updates. 
This Repo is Dead?

**Comment by izuzak** [comment]
@SduyXD This package is not being developed at the moment, as indicated in the [README](https://github.com/atom/terminal#atom-terminal-package) and in [this comment](https://github.com/atom/terminal/issues/28#issuecomment-44027534).

We'll probably get back to it in the future, but can't promise when that will happen. Sorry for the confusion!
